spring:
  thymeleaf:
    mode: HTML
  profiles:
    active: dev
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true
  messages:
    basename: i18n/messages

comment.avatar: /images/avatar.jpg